import { exec } from "child_process";
import { promisify } from "util";

const execAsync = promisify(exec);

/**
 * Perform a real web search using agent-browser (browser automation) 
 * or fallback to DuckDuckGo Lite scraping
 */
export async function performWebSearch(query: string): Promise<{
  results: Array<{ title: string; snippet: string; url: string }>;
  raw?: string;
}> {
  const results: Array<{ title: string; snippet: string; url: string }> = [];
  
  try {
    // Try agent-browser first for real browser-based search
    const { stdout } = await execAsync(
      `agent-browser goto "https://lite.duckduckgo.com/lite/?q=${encodeURIComponent(query)}" --wait 3 --extract-text 2>&1`,
      { timeout: 15000 }
    );
    
    // Parse the extracted text for links and snippets
    const lines = stdout.split("\n");
    let currentTitle = "";
    
    for (const line of lines) {
      const linkMatch = line.match(/https?:\/\/[^\s"'<>]+/g);
      if (linkMatch) {
        const url = linkMatch[0];
        // Get the surrounding text as a snippet
        const before = lines[Math.max(0, lines.indexOf(line) - 1)] || "";
        const snippet = before.trim().substring(0, 200);
        
        results.push({
          title: currentTitle || url.substring(0, 60),
          snippet,
          url,
        });
        currentTitle = "";
      } else if (line.trim().length > 30 && line.trim().length < 200) {
        currentTitle = line.trim();
      }
    }
  } catch (e) {
    // Fallback: use curl for simple search
    try {
      const { stdout } = await execAsync(
        `curl -s -L "https://lite.duckduckgo.com/lite/?q=${encodeURIComponent(query)}" 2>&1`,
        { timeout: 10000 }
      );
      
      // Extract result links from the HTML
      const linkRegex = /<a[^>]*href="([^"]*)"[^>]*>([^<]*)<\/a>/gi;
      let match;
      while ((match = linkRegex.exec(stdout)) !== null) {
        const url = match[1].startsWith("http") ? match[1] : `https://${match[1]}`;
        const title = match[2].trim();
        if (title && url && !url.includes("duckduckgo.com") && !url.includes("https://www.")) {
          results.push({ title: title.substring(0, 100), snippet: "", url });
        }
        if (results.length >= 20) break;
      }
    } catch (curlErr) {
      console.error("Web search fallback failed:", curlErr);
    }
  }

  return { results };
}

/**
 * Generate a simple HTML page and save it to the webpages directory
 */
export async function generateWebpage(
  title: string,
  content: string,
  theme: "modern" | "minimal" | "luxury" = "modern"
): Promise<{ path: string; url: string }> {
  const fs = await import("fs/promises");
  const path = await import("path");
  
  const pagesDir = path.join(process.cwd(), "public", "generated");
  await fs.mkdir(pagesDir, { recursive: true });

  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .substring(0, 40) || "page";

  const themes: Record<string, string> = {
    modern: `body { font-family: system-ui; max-width: 800px; margin: 0 auto; padding: 2rem; background: #0a0a0a; color: #e5e5e5; line-height: 1.6; }
      h1 { color: #8b5cf6; font-size: 2.5rem; } h2 { color: #14b8a6; } a { color: #8b5cf6; }
      .card { background: #1a1a2e; border-radius: 12px; padding: 1.5rem; margin: 1rem 0; border: 1px solid #2a2a3e; }`,
    minimal: `body { font-family: 'Georgia', serif; max-width: 650px; margin: 0 auto; padding: 2rem; background: #fafafa; color: #333; line-height: 1.8; }
      h1 { color: #000; font-size: 2rem; } a { color: #0066cc; }`,
    luxury: `body { font-family: 'Playfair Display', Georgia, serif; max-width: 900px; margin: 0 auto; padding: 3rem; background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: #e8dcc8; line-height: 1.7; }
      h1 { color: #c9a96e; font-size: 3rem; font-weight: 400; } h2 { color: #d4af37; }
      .card { background: rgba(255,255,255,0.05); border-radius: 16px; padding: 2rem; margin: 1.5rem 0; border: 1px solid rgba(201,169,110,0.2); }
      .highlight { color: #d4af37; }`,
  };

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} | AutoExec</title>
  <style>${themes[theme] || themes.modern}</style>
</head>
<body>
  <h1>${title}</h1>
  ${content}
  <hr style="margin-top: 3rem; border-color: rgba(255,255,255,0.1);">
  <p style="text-align: center; color: #666; font-size: 0.8rem;">Generated by AutoExec AI · ${new Date().toLocaleDateString()}</p>
</body>
</html>`;

  const filename = `${slug}.html`;
  await fs.writeFile(path.join(pagesDir, filename), html, "utf-8");

  return {
    path: path.join(pagesDir, filename),
    url: `/generated/${filename}`,
  };
}

/**
 * Classify a task with expanded support for new capabilities
 */
export function classifyTask(description: string): {
  type: "research" | "list_building" | "email_outreach" | "data_gathering" | "marketing" | "webpage" | "image_gen" | "cross_promotion" | "general";
  targets: string[];
  location?: string;
  industry?: string;
} {
  const lower = description.toLowerCase();

  let type: "research" | "list_building" | "email_outreach" | "data_gathering" | "marketing" | "webpage" | "image_gen" | "cross_promotion" | "general" = "general";
  
  if (lower.includes("find") || lower.includes("search") || lower.includes("research") || lower.includes("scrape") || lower.includes("locate")) {
    type = "research";
  }
  if (lower.includes("list") || lower.includes("compile") || lower.includes("extract") || lower.includes("csv") || lower.includes("spreadsheet")) {
    type = "list_building";
  }
  if (lower.includes("email") || lower.includes("outreach") || lower.includes("draft") || lower.includes("pitch") || lower.includes("intro") || lower.includes("send email")) {
    type = "email_outreach";
  }
  if (lower.includes("gather") || lower.includes("analyze") || lower.includes("collect") || lower.includes("data") || lower.includes("intel") || lower.includes("research market")) {
    type = "data_gathering";
  }
  if (lower.includes("marketing") || lower.includes("advertise") || lower.includes("ad ") || lower.includes("traffic") || lower.includes("promote") || lower.includes("marketing channel")) {
    type = "marketing";
  }
  if (lower.includes("webpage") || lower.includes("landing page") || lower.includes("build") && !lower.includes("list") && !lower.includes("find") || lower.includes("create page") || lower.includes("html page")) {
    type = "webpage";
  }
  if (lower.includes("image") || lower.includes("ad creative") || lower.includes("banner") || lower.includes("graphic") || lower.includes("visual")) {
    type = "image_gen";
  }
  if (lower.includes("cross-promote") || lower.includes("one post ai") || lower.includes("cross promote") || lower.includes("other product") || lower.includes("promote my other")) {
    type = "cross_promotion";
  }

  // Extract potential targets
  const targets: string[] = [];
  const targetPatterns = [
    /(?:saas|startups?|companies|businesses|firms|agencies|vendors)/gi,
    /(\w+)\s+(?:companies|startups|firms)/gi,
  ];
  for (const pattern of targetPatterns) {
    const matches = description.match(pattern);
    if (matches) targets.push(...matches);
  }

  // Extract location
  let location: string | undefined;
  const locPattern = /in\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)/g;
  const locMatch = locPattern.exec(description);
  if (locMatch && locMatch[1].length < 30) {
    location = locMatch[1];
  }

  return { type, targets: Array.from(new Set(targets)), location };
}

/**
 * FAQ / Support knowledge base for the in-app support assistant
 */
export const faqKnowledge: Array<{ keywords: string[]; answer: string; category: string }> = [
  {
    keywords: ["pricing", "cost", "price", "plans", "subscription", "how much", "monthly", "annual", "discount"],
    category: "pricing",
    answer:
      "AutoExec offers three plans:\n\n" +
      "**Starter** — $39/mo\n- 50 tasks per month\n- Basic web research & email\n\n" +
      "**Pro** — $99/mo\n- 200 tasks per month\n- Deep web research & scraping\n- Multi-step email outreach\n- Priority processing\n\n" +
      "**Unlimited** — $249/mo\n- No task cap\n- All features + priority\n- Dedicated support\n\n" +
      "💰 **Save ~20%** with annual billing! You can upgrade or downgrade anytime from the Billing page."
  },
  {
    keywords: ["free trial", "trial", "try", "demo", "get started", "sign up", "signup"],
    category: "getting-started",
    answer:
      "Getting started with AutoExec is easy! 🚀\n\n" +
      "1. Click **Launch App** on the homepage\n" +
      "2. Create your account (or sign in with a demo account)\n" +
      "3. Start a **new chat** from the dashboard\n" +
      "4. Type what you need done in plain language\n\n" +
      "**Try these examples:**\n" +
      "- \"Find me 5 SaaS companies hiring in San Francisco\"\n" +
      "- \"Build me a landing page for my startup\"\n" +
      "- \"Research the best marketing channels for my product\"\n" +
      "- \"What's my task limit?\"\n\n" +
      "You can explore the dashboard and submit test tasks right away!"
  },
  {
    keywords: ["task limit", "task limits", "how many tasks", "limit", "overage", "exceed"],
    category: "usage",
    answer:
      "Each plan has a monthly task limit:\n\n" +
      "- **Starter**: 50 tasks/month\n" +
      "- **Pro**: 200 tasks/month\n" +
      "- **Unlimited**: No limit\n\n" +
      "You can see your current usage on the dashboard. If you approach your limit, we notify you. " +
      "No overage fees — tasks simply pause until the next cycle or you upgrade. " +
      "Upgrade anytime from the **Billing** page!"
  },
  {
    keywords: ["cancel", "cancellation", "refund", "unsubscribe", "stop"],
    category: "billing",
    answer:
      "You can cancel your subscription anytime from the **Billing** page in your dashboard. " +
      "Your plan remains active until the end of the current billing period. " +
      "No cancellation fees, no hassle. We'll miss you though! 😊"
  },
  {
    keywords: ["how to", "how do i", "how can i", "tutorial", "guide", "help me", "walk me through"],
    category: "how-to",
    answer:
      "Here are quick guides for common tasks:\n\n" +
      "**🤖 Research companies**\n" +
      "Just say: \"Find me [number] [type] companies in [location]\"\n\n" +
      "**📧 Send outreach emails**\n" +
      "Say: \"Draft an intro email to [target] about [topic]\"\n\n" +
      "**🌐 Build a webpage**\n" +
      "Say: \"Build me a landing page for [your product]\"\n\n" +
      "**📊 Marketing research**\n" +
      "Say: \"Research the best channels to advertise [product]\"\n\n" +
      "**🤝 Cross-promotion**\n" +
      "Say: \"Tell me about One Post AI\" to see our sister product!\n\n" +
      "AutoExec responds with real-time streaming results. Just describe what you need!"
  },
  {
    keywords: ["what is autoexec", "what can autoexec do", "features", "capabilities", "can it"],
    category: "features",
    answer:
      "AutoExec is your autonomous AI executive assistant. I can:\n\n" +
      "🔍 **Web Research** — Search the web for companies, people, data\n" +
      "📋 **List Building** — Compile prospect lists with verified contacts\n" +
      "✉️ **Email Outreach** — Draft personalized email campaigns\n" +
      "📊 **Market Research** — Analyze channels, competitors, trends\n" +
      "🌐 **Webpage Building** — Generate and host landing pages\n" +
      "🎨 **Ad Creative** — Research and recommend ad strategies\n" +
      "🤝 **Cross-Promotion** — Connect with One Post AI\n\n" +
      "Just describe what you need in plain language and I'll handle the rest!"
  },
  {
    keywords: ["one post ai", "onepost", "social media", "sister product", "cross promote", "cross-promotion"],
    category: "cross-promotion",
    answer:
      "**One Post AI** is our sister product for social media management! 🚀\n\n" +
      "Features:\n" +
      "- ✍️ AI-powered content generation (posts, captions, threads)\n" +
      "- 📅 Smart scheduling at peak engagement times\n" +
      "- 📊 Analytics to track what works\n" +
      "- 🔄 Cross-platform management (Twitter, LinkedIn, Instagram)\n\n" +
      "🎉 **Exclusive AutoExec discount:** Get **20% off** One Post AI!\n" +
      "Use code **AUTOEXEC20** at checkout.\n" +
      "👉 [Visit One Post AI →](https://onepost.ai/autoexec)"
  },
  {
    keywords: ["affiliate", "referral", "commission", "earn money", "partner", "promote"],
    category: "affiliate",
    answer:
      "Yes! Our **Affiliate Program** pays **10% recurring commission** on every referral. 🎉\n\n" +
      "How it works:\n" +
      "1. Share your unique affiliate link\n" +
      "2. Someone clicks and subscribes\n" +
      "3. You earn 10% every month\n\n" +
      "Perfect for content creators, UGC creators, and entrepreneurs.\n" +
      "Visit our [Affiliates page](/affiliates) for more details or contact us to apply!"
  },
  {
    keywords: ["contact", "support", "help", "human", "talk to", "email support", "customer service"],
    category: "support",
    answer:
      "I'm here to help! But if you need human assistance:\n\n" +
      "📧 **Email:** support@autoexec.ai\n" +
      "💬 **Chat:** You're talking to it! I can answer most questions.\n" +
      "🌐 **FAQ:** Visit our [FAQ page](/faq) for common questions.\n\n" +
      "We typically respond to emails within 24 hours."
  },
  {
    keywords: ["security", "data", "privacy", "safe", "encrypt", "gdpr", "secure"],
    category: "security",
    answer:
      "Your data security is our top priority. 🔒\n\n" +
      "- All data encrypted **in transit** (TLS) and **at rest**\n" +
      "- Industry-standard security practices\n" +
      "- Your research data, contacts, and drafts are **private to you**\n" +
      "- We never share your data with third parties\n\n" +
      "AutoExec runs in secure cloud environments. Your tasks and results are yours alone."
  },
  {
    keywords: ["who built", "who created", "company", "team", "about", "story", "founded"],
    category: "about",
    answer:
      "AutoExec was built by a team passionate about empowering busy entrepreneurs, solo founders, and empire-builders. " +
      "We believe AI should handle the grunt work so humans can focus on what matters.\n\n" +
      "Visit our [About page](/about) to learn more about our mission!"
  },
];

/**
 * Check if a message is a support/question rather than a task to execute
 */
export function isSupportQuestion(message: string): { isSupport: boolean; answer?: string; category?: string } {
  const lower = message.toLowerCase().trim();

  // Check for pure conversational/support patterns (not task-oriented)
  const supportPatterns = [
    /^(what|how|why|when|where|who|which|can|could|would|will|do|does|did|is|are|was|were)\s/i,
    /^(hi|hello|hey|thanks|thank you|okay|ok|sure|yes|no|good|great)\b/i,
    /^i (have|need|want|am|was|would like to know)/i,
    /tell me about/i,
    /explain/i,
    /what is/i,
    /how (do|does|can|to)/i,
    /(help|support|question|faq)/i,
  ];

  const isGeneralQuestion = supportPatterns.some(p => p.test(lower));
  
  // Also check if the message looks like a task (contains actionable keywords)
  const taskPatterns = [
    /find (\d+|me|us)/i,
    /search (for|the)/i,
    /scrape/i,
    /build (me|a|an)/i,
    /create (a|an|me)/i,
    /generate/i,
    /draft/i,
    /send (an|a|email)/i,
    /research (\d+|the|these)/i,
    /compile/i,
    /extract/i,
    /list (\d+|the|of)/i,
    /locate/i,
  ];
  
  const isTaskLike = taskPatterns.some(p => p.test(lower));

  // If it looks like a general question without task intent, treat as support
  if (isGeneralQuestion && !isTaskLike) {
    // Find the best matching FAQ
    let bestMatch: { answer: string; category: string; score: number } | null = null;

    for (const faq of faqKnowledge) {
      let score = 0;
      for (const kw of faq.keywords) {
        if (lower.includes(kw.toLowerCase())) {
          score += kw.length; // Longer keyword matches are better
        }
      }
      if (score > 0 && (!bestMatch || score > bestMatch.score)) {
        bestMatch = { answer: faq.answer, category: faq.category, score };
      }
    }

    if (bestMatch) {
      return { isSupport: true, answer: bestMatch.answer, category: bestMatch.category };
    }

    // Default helpful response for unrecognized questions
    return {
      isSupport: true,
      answer:
        "I'm AutoExec, your AI executive assistant! 🤖\n\n" +
        "I can help you with:\n" +
        "• **Research** — finding companies, people, and data on the web\n" +
        "• **List building** — compiling prospect lists with contacts\n" +
        "• **Email outreach** — drafting personalized campaigns\n" +
        "• **Marketing research** — analyzing channels and strategies\n" +
        "• **Webpage building** — generating landing pages\n" +
        "• **Answering questions** — about AutoExec, pricing, and how-tos\n\n" +
        "What would you like me to do? Just describe your task or ask me anything!"
    };
  }

  return { isSupport: false };
}