'use client';

import React from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Bot } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <header className="fixed top-0 left-0 right-0 z-50 glass border-b border-slate-900 px-6 py-4 flex items-center justify-between">
        <Link href="/" className="flex items-center space-x-2">
          <div className="h-9 w-9 bg-brand-500 rounded-lg flex items-center justify-center shadow-lg shadow-brand-500/20">
            <Bot className="h-5 w-5 text-white" />
          </div>
          <span className="text-xl font-bold tracking-tight text-white font-serif">Axel AI™</span>
        </Link>
        <Link href="/dashboard"><Button variant="primary" size="sm">Dashboard</Button></Link>
      </header>
      <main className="pt-32 pb-24 px-6 max-w-4xl mx-auto">
        <div className="mb-12"><h1 className="text-5xl font-extrabold tracking-tight mb-4 font-serif">Terms of Service</h1><p className="text-slate-400 text-sm">Last updated: July 4, 2026</p></div>
        <div className="space-y-6 text-slate-300 leading-relaxed">
          <section><h2 className="text-2xl font-bold text-white mb-3 font-serif">1. Acceptance of Terms</h2>
          <p>By using Axel AI (&quot;the Service&quot;), you agree to these Terms. Axel AI is a product of <strong className="text-white">Aura Haven Tech</strong>. If you do not agree, do not use the Service.</p></section>
          <section><h2 className="text-2xl font-bold text-white mb-3 font-serif">2. Service Description</h2>
          <p>Axel AI is an autonomous AI executive assistant that executes business tasks — research, content creation, email outreach, data gathering, storefront building, and analytics. Features include AI chat, task execution, business organizer, marketing engine, and storefront builder. We reserve the right to modify features with reasonable notice.</p></section>
          <section><h2 className="text-2xl font-bold text-white mb-3 font-serif">3. Account & Subscriptions</h2>
          <p>You must be 18+ to use the Service. Paid plans ($39/mo Starter, $99/mo Pro, $249/mo Unlimited) are billed monthly. All plans include a 30-day money-back guarantee. See our <Link href="/refund" className="text-brand-400 hover:text-brand-300">Refund Policy</Link>. Payments via Stripe.</p></section>
          <section><h2 className="text-2xl font-bold text-white mb-3 font-serif">4. User Responsibilities</h2>
          <p>You are responsible for: reviewing AI outputs before use, complying with laws, maintaining account security, and not using the Service for illegal activities. You retain rights to content you create.</p></section>
          <section><h2 className="text-2xl font-bold text-white mb-3 font-serif">5. Intellectual Property & Trademark Protection</h2>
          <p><strong className="text-white">Axel AI™</strong> and <strong className="text-white">OnePost AI™</strong> are trademarks of <strong className="text-white">Aura Haven Tech</strong>. All software, branding, logos, trade dress, content, and materials provided through the Service are the exclusive intellectual property of Aura Haven Tech and are protected by copyright, trademark, and other applicable intellectual property laws.</p>
          <p className="mt-3">No license, express or implied, is granted to use any trademark, service mark, trade name, or logo of Aura Haven Tech without prior written consent. You may not copy, modify, reverse engineer, distribute, sell, or create derivative works of the Service or any part thereof. Unauthorized use of any Aura Haven Tech intellectual property may result in legal action, including but not limited to claims for trademark infringement, copyright infringement, and unfair competition.</p>
          <p className="mt-3">All content generated by the Service is provided for your internal business use. You retain no ownership or license rights to the underlying AI models, algorithms, or technology. &copy; 2026 Aura Haven Tech. All rights reserved.</p></section>
          <section><h2 className="text-2xl font-bold text-white mb-3 font-serif">6. AI Outputs</h2>
          <p>AI-generated outputs are provided as assistance tools. Axel AI™ is not responsible for the accuracy or legality of AI outputs. You should review and verify all AI-generated content before use, especially for business-critical decisions.</p></section>
          <section><h2 className="text-2xl font-bold text-white mb-3 font-serif">7. Limitation of Liability</h2>
          <p>Service provided &quot;as is.&quot; Aura Haven Tech is not liable for damages arising from use. Our total liability is limited to the amount paid in the preceding 12 months.</p></section>
          <section><h2 className="text-2xl font-bold text-white mb-3 font-serif">8. Contact</h2>
          <p>Email: <a href="mailto:aurahaven@gmail.com" className="text-brand-400 hover:text-brand-300">aurahaven@gmail.com</a></p></section>
        </div>
      </main>
    </div>
  );
}